/**
 * Created by nigonzalez on 12/25/15.
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 *
 */
object Problem2 {

    def loop(acc: Int, x0: Int, x1: Int): Int = {
        val x2 = x0 + x1
        if (x2 > 4000000) acc
        else loop(if (x2 % 2 == 0) acc + x2 else acc, x1, x2)
    }

    def main(args: Array[String]): Unit = {
        println(loop(2, 1, 2))
    }

}
